// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpdhjovsdmwdoehtpcce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZGhqb3ZzZG13ZG9laHRwY2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTcxNDIsImV4cCI6MjA3NDU3MzE0Mn0.m0jdKmGeWr9Vhw69LoYJDUgbsZCouoafxmuzbR5p4fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});